# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'craveBot' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.0.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Koloda'
  pod 'SwiftLocation', '~> 3.2.3'
  pod 'Toolbar'
  pod 'FloatRatingView'
  pod 'Kingfisher'
  pod 'CLTypingLabel'
  pod 'lottie-ios'
 #pod 'Alamofire-SwiftyJSON'

  # Pods for craveBot

  target 'craveBotTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'craveBotUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
