# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'craveBot' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.0.0-beta.5'
  pod 'SwiftyJSON', '~> 4.0'
  pod "Koloda"
  pod 'SwiftLocation', '~> 3.2.3'
  pod 'Toolbar'

  # Pods for craveBot

  target 'craveBotTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'craveBotUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
